# Generated by Django 3.2.7 on 2021-09-10 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_assinado_sign'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assinado',
            old_name='sign',
            new_name='signature',
        ),
    ]
